### PR TITLE
do not use the default implementation and add functionality relied on from it

### PR DESCRIPTION
**Pull request by lukeapage**
I am currently looking at supporting export but this came up.

### CODE REVIEW

**Comment by lukeapage** [comment]
@finom added export. Please let me know if you like the idea of this.

**Comment by finom** [comment]
@lukeapage thank you, but I even cannot look on it, have hard days on my job. I'm going to reply as soon as I can. Sorry.

**Comment by finom** [comment]
Hey, I have merged the first PR but this one got conflicts. Can you resolve them?

**Comment by finom** [comment]
@lukeapage just checked it and everything looks fantastic. You've done great job. Please fix merge issues and I'll add you as another owner on NPM so you don't need to wait me to publish it.

**Comment by lukeapage** [comment]
@finom thanks, I've rebased.
My npm username is "agatronic" but if you would like to give me access it would be good to have access to the repo too, so that the repo would always match what was published. and I hope there aren't any more changes needed but we'll see - I've switched to using this on a large project and it appears to be fine, but something might come up in the next couple of weeks.

**Comment by finom** [comment]
@lukeapage cool. Just added you both to NPM and to the repo. Thank you.

**Pull request merged**
